### PR TITLE
Fixed new quest filtering

### LINKED ISSUE #343: Bug : Current filter doesn't apply to newly created quest

### PR DESCRIPTION
**Pull request by kafann**
close #343

### CODE REVIEW

File: packages/react-app/src/tokens.ts [hunk 1]
```diff
@@ -62,7 +62,7 @@ export const TOKENS = Object.freeze({
       name: 'Dai Stablecoin',
       symbol: 'DAI',
       token: '0xdc31Ee1784292379Fbb2964b3B9C4124D8F89C60',
-      decimals: 6,
```
Comment (Corantin) [inline packages/react-app/src/tokens.ts:65]: Nice catch

File: packages/react-app/src/components/views/quest-list.tsx [hunk 2]
```diff
@@ -141,6 +141,7 @@ export default function QuestList() {
       if (newQuest) {
         setQuests([newQuest, ...quests]);
         setNewQuestLoading(false);
+        refresh(filter);
```
Comment (Corantin) [inline packages/react-app/src/components/views/quest-list.tsx:144]: I dont like that much the whole refresh, I would rather go with a full check of the filter like this

 if (
          (filter.status === ENUM_QUEST_STATE.All || newQuest.state === filter.status) &&
          filter.title &&
          filter.title.includes(newQuest.title!) &&
          filter.description &&
          filter.description.includes(newQuest.description!) &&
          filter.minExpireTime &&
          filter.minExpireTime <= newQuest.expireTime
        ) {
          setQuests([newQuest, ...quests]);
        }

**Review by Corantin — CHANGES_REQUESTED** [review]
