### PR TITLE
create modal close and no result fixed

### LINKED ISSUE #344: Bug : modal closes after quest confirmation

### LINKED ISSUE #345: Bug : After creating a quest, create button not there

### PR DESCRIPTION
**Pull request by kafann**
close #345  
close #344

### CODE REVIEW

File: packages/react-app/src/components/views/quest-list.tsx [hunk 1]
```diff
@@ -194,7 +194,9 @@ export default function QuestList() {
         next={loadMore}
         hasMore={hasMore}
         endMessage={
-          quests.length || newQuestLoading ? (
+          // quests.length || newQuestLoading ? (
```
Comment (Corantin) [inline packages/react-app/src/components/views/quest-list.tsx:197]:
```suggestion
```

File: packages/react-app/src/components/views/quest-list.tsx [hunk 2]
```diff
@@ -220,7 +222,7 @@ export default function QuestList() {
               <Quest isSummary questData={questData} isLoading={!questData.address} />
             </QuestWrapperStyled>
           ))}
-          {isLoading && skeletonQuests}
+          {/* {isLoading && skeletonQuests} */}
```
Comment (Corantin) [inline packages/react-app/src/components/views/quest-list.tsx:225]: Restore
```suggestion
          {isLoading && skeletonQuests}
```

**Review by Corantin — CHANGES_REQUESTED** [review]
